name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the Docker image (e.g., 1.0.0)'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image with version and latest tags
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/filament-tracker:${{ github.event.inputs.version }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/filament-tracker:${{ github.event.inputs.version }} ${{ secrets.DOCKER_USERNAME }}/filament-tracker:latest

    # Step 4: Push both tags to Docker Hub
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/filament-tracker:${{ github.event.inputs.version }}
        docker push ${{ secrets.DOCKER_USERNAME }}/filament-tracker:latest
